export const ORDERS_ALL_ACTIONS = {
  START: "ORDERS_ALL_START",
  OPEN: "ORDERS_ALL_OPEN",
  END: "ORDERS_ALL_END",
  SUCCESS: "ORDERS_ALL_SUCCESS",
  ERROR: "ORDERS_ALL_ERROR",
  CLOSED: "ORDERS_ALL_CLOSED",
  MESSAGE: "ORDERS_ALL_MESSAGE",
} as const;

export const ORDERS_USER_ACTIONS = {
  START: "ORDERS_USER_START",
  OPEN: "ORDERS_USER_OPEN",
  END: "ORDERS_USER_END",
  SUCCESS: "ORDERS_USER_SUCCESS",
  ERROR: "ORDERS_USER_ERROR",
  CLOSED: "ORDERS_USER_CLOSED",
  MESSAGE: "ORDERS_USER_MESSAGE",
} as const;
