export const LOAD_DATA_START = "LOAD_DATA_START";
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const LOAD_DATA_ERROR = "LOAD_DATA_ERROR";
export const SET_BUN = "SET_BUN";
export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const DELETE_INGREDIENT = "DELETE_INGREDIENT";
export const SWAP_INGREDIENTS = "SWAP_INGREDIENTS";
export const SET_SUM = "SET_SUM";

export const CREATE_ORDER_START = "CREATE_ORDER_START";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
export const CLEAR_ORDER = "CLEAR_ORDER";

export const SET_DISPLAYED_INGREDIENT = "SET_DISPLAYED_INGREDIENT";
export const SET_TAB = "SET_TAB";
