export const CONSTRUCTOR_ACTIONS = {
  SELECT_BUN: "SELECT_BUN",
  ADD_INGREDIENT: "ADD_INGREDIENT",
  REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
  REORDER_INGREDIENTS: "REORDER_INGREDIENTS",
  CLEAN_ORDER: "CLEAN_ORDER",
};

export const TAB_ACTIONS = {
  CHANGE_TAB: "CHANGE_TAB",
};
